### ISSUE TITLE
System.MissingMethodException: Attempted to access a missing method.

### ISSUE THREAD

**Issue by Rekandy** [maxisoft/ASFFreeGames#46] opened 2023-11-07 12:50 UTC
**Bug description**
Errors when logging into accounts

**To Reproduce**
1.Installing plugin version 1.4.1
2.Running ASF and getting an error when logging into bot accounts (as shown on the screenshot)

**Screenshots**
![ArchiSteamFarm_i7coVylSWl](https://github.com/maxisoft/ASFFreeGames/assets/77551516/b17b0ef2-2634-49ed-a873-b2c0459f0a9c)

Desktop :
OS: Windows 10
Browser chrome
Version 1.4.1

**Comment by HaxXorHardy** [comment] 2023-11-19 10:52
`2023-11-19T10:49:17.360580618Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitCore() ArchiSteamFarm V5.4.13.4 (linux-x64/3e2dbd0e-e452-4f79-a720-105bf6d28363 | .NET 7.0.13; debian.11-x64; Linux 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29))
2023-11-19T10:49:17.375809652Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitCore() Copyright © 2015-2023 JustArchiNET
2023-11-19T10:49:17.716550529Z 2023-11-19 10:49:17|ArchiSteamFarm-18|WARN|ASF|Load() Your IPC password seems to be weak. Consider choosing a stronger one for increased security. Details: Add another word or two.  Uncommon words are better. Reversed words aren't much harder to guess.
2023-11-19T10:49:17.731930680Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() Initializing Plugins...
2023-11-19T10:49:17.779967712Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() Loading ASFFreeGamesPlugin V1.4.1.0...
2023-11-19T10:49:17.780144812Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|OnLoaded() Loaded ASFFreeGamesPlugin
2023-11-19T10:49:17.780527337Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() ASFFreeGamesPlugin has been loaded successfully!
2023-11-19T10:49:17.780724860Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() Loading ItemsMatcherPlugin V5.4.13.4...
2023-11-19T10:49:17.780908010Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() ItemsMatcherPlugin has been loaded successfully!
2023-11-19T10:49:17.781065197Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() Loading MobileAuthenticatorPlugin V5.4.13.4...
2023-11-19T10:49:17.781221702Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() MobileAuthenticatorPlugin has been loaded successfully!
2023-11-19T10:49:17.781362933Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() Loading SteamTokenDumperPlugin V5.4.13.4...
2023-11-19T10:49:17.781540213Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() SteamTokenDumperPlugin has been loaded successfully!
2023-11-19T10:49:17.782845838Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|InitPlugins() You've loaded one or multiple custom plugins into ASF. Since we're unable to offer support for modded setups, please contact the appropriate developers of the plugins that you decided to use in case of any issues.
2023-11-19T10:49:17.809028466Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|UpdateAndRestart() ASF will automatically check for new versions every 1 day.
2023-11-19T10:49:17.811386110Z 2023-11-19 10:49:17|ArchiSteamFarm-18|INFO|ASF|Update() Checking for new version...
2023-11-19T10:49:19.711527883Z 2023-11-19 10:49:19|ArchiSteamFarm-18|INFO|ASF|Update() Local version: 5.4.13.4 | Remote version: 5.4.13.4
2023-11-19T10:49:19.815259945Z 2023-11-19 10:49:19|ArchiSteamFarm-18|INFO|ASF|OnASFInit() SteamTokenDumperPlugin is currently disabled according to your configuration. If you'd like to help SteamDB in data submission, please check out our wiki.
2023-11-19T10:49:19.835072278Z 2023-11-19 10:49:19|ArchiSteamFarm-18|INFO|ASF|Start() Starting IPC server...
2023-11-19T10:49:20.154917783Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:1242
2023-11-19T10:49:20.158488799Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-11-19T10:49:20.159058537Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2023-11-19T10:49:20.159095006Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|Microsoft.Hosting.Lifetime|Content root path: /app
2023-11-19T10:49:20.159316206Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|ASF|Start() IPC server ready!
2023-11-19T10:49:20.197889702Z 2023-11-19 10:49:20|ArchiSteamFarm-18|WARN|ASF|Load() Your Steam password for 'pd3' seems to be weak. Consider choosing a stronger one for increased security. Details: Add another word or two.  Uncommon words are better.
2023-11-19T10:49:20.199053878Z 2023-11-19 10:49:20|ArchiSteamFarm-18|WARN|ASF|Load() Your Steam password for 'aw' seems to be weak. Consider choosing a stronger one for increased security. Details: Add another word or two.  Uncommon words are better.
2023-11-19T10:49:20.199065607Z 2023-11-19 10:49:20|ArchiSteamFarm-18|WARN|ASF|Load() Your Steam password for 'beach' seems to be weak. Consider choosing a stronger one for increased security. Details: Add another word or two.  Uncommon words are better.
2023-11-19T10:49:20.199095015Z 2023-11-19 10:49:20|ArchiSteamFarm-18|WARN|ASF|Load() Your Steam password for 'bo3' seems to be weak. Consider choosing a stronger one for increased security. Details: Add another word or two.  Uncommon words are better.
2023-11-19T10:49:20.199119254Z 2023-11-19 10:49:20|ArchiSteamFarm-18|WARN|ASF|Load() Your Steam password for 'csgo' seems to be weak. Consider choosing a stronger one for increased security. Details: Add another word or two.  Uncommon words are better.
2023-11-19T10:49:20.264878191Z 2023-11-19 10:49:20|ArchiSteamFarm-18|ERROR|csgo|.ctor() You've attempted to use paid feature MatchActively but you don't have a valid LicenseID set in the ASF global config. Please review your configuration, as the functionality won't work without additional details.
2023-11-19T10:49:20.266252729Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|pd3|Start() Starting...
2023-11-19T10:49:20.266273863Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|bo3|Start() Starting...
2023-11-19T10:49:20.266290009Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|aw|Start() Starting...
2023-11-19T10:49:20.266341022Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|beach|Start() Starting...
2023-11-19T10:49:20.266399347Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|csgo|Start() Starting...
2023-11-19T10:49:20.268424235Z 2023-11-19 10:49:20|ArchiSteamFarm-18|INFO|bo3|Connect() Connecting...
2023-11-19T10:49:24.952266419Z 2023-11-19 10:49:24|ArchiSteamFarm-18|INFO|bo3|OnConnected() Connected to Steam!
2023-11-19T10:49:24.957819341Z 2023-11-19 10:49:24|ArchiSteamFarm-18|INFO|bo3|OnConnected() Logging in...
2023-11-19T10:49:25.526555219Z 2023-11-19 10:49:25|ArchiSteamFarm-18|INFO|bo3|OnLoggedOn() Successfully logged on as ####
2023-11-19T10:49:25.540042982Z 2023-11-19 10:49:25|ArchiSteamFarm-18|INFO|bo3|Init() Success!
2023-11-19T10:49:25.574679232Z 2023-11-19 10:49:25|ArchiSteamFarm-18|ERROR|ASF|OnBotLoggedOn() System.MissingMethodException: Method not found: 'UInt32 System.BitConverter.ToUInt32(System.ReadOnlySpan`1<Byte>)'.
2023-11-19T10:49:25.574749586Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextDouble()
2023-11-19T10:49:25.574763188Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextGaussian(Double mean, Double standardDeviation)
2023-11-19T10:49:25.574766013Z    at Maxisoft.ASF.CollectIntervalManager.GetRandomizedTimerDelay(Double meanSeconds, Double stdSeconds, Double minSeconds, Double maxSeconds)
2023-11-19T10:49:25.574768316Z    at Maxisoft.ASF.CollectIntervalManager.StartTimerIfNeeded()
2023-11-19T10:49:25.574770319Z    at Maxisoft.ASF.ASFFreeGamesPlugin.StartTimerIfNeeded()
2023-11-19T10:49:25.574772243Z    at Maxisoft.ASF.ASFFreeGamesPlugin.RegisterBot(Bot bot)
2023-11-19T10:49:25.574774176Z    at Maxisoft.ASF.ASFFreeGamesPlugin.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:25.574776660Z    at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
2023-11-19T10:49:25.574778703Z    at ArchiSteamFarm.Plugins.PluginsCore.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:27.665690476Z 2023-11-19 10:49:27|ArchiSteamFarm-18|INFO|bo3|IsAnythingToFarm() Checking first badge page...
2023-11-19T10:49:28.531990063Z 2023-11-19 10:49:28|ArchiSteamFarm-18|INFO|bo3|StartFarming() We don't have anything to farm on this account!
2023-11-19T10:49:30.270158557Z 2023-11-19 10:49:30|ArchiSteamFarm-18|INFO|pd3|Connect() Connecting...
2023-11-19T10:49:32.489187038Z 2023-11-19 10:49:32|ArchiSteamFarm-18|INFO|pd3|OnConnected() Connected to Steam!
2023-11-19T10:49:32.489209544Z 2023-11-19 10:49:32|ArchiSteamFarm-18|INFO|pd3|OnConnected() Logging in...
2023-11-19T10:49:33.039142633Z 2023-11-19 10:49:33|ArchiSteamFarm-18|INFO|pd3|OnLoggedOn() Successfully logged on as #####
2023-11-19T10:49:33.039158058Z 2023-11-19 10:49:33|ArchiSteamFarm-18|INFO|pd3|Init() Success!
2023-11-19T10:49:33.042806403Z 2023-11-19 10:49:33|ArchiSteamFarm-18|ERROR|ASF|OnBotLoggedOn() System.MissingMethodException: Method not found: 'UInt32 System.BitConverter.ToUInt32(System.ReadOnlySpan`1<Byte>)'.
2023-11-19T10:49:33.042821097Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextDouble()
2023-11-19T10:49:33.042826996Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextGaussian(Double mean, Double standardDeviation)
2023-11-19T10:49:33.042833777Z    at Maxisoft.ASF.CollectIntervalManager.GetRandomizedTimerDelay(Double meanSeconds, Double stdSeconds, Double minSeconds, Double maxSeconds)
2023-11-19T10:49:33.042838775Z    at Maxisoft.ASF.CollectIntervalManager.StartTimerIfNeeded()
2023-11-19T10:49:33.042843082Z    at Maxisoft.ASF.ASFFreeGamesPlugin.StartTimerIfNeeded()
2023-11-19T10:49:33.042847118Z    at Maxisoft.ASF.ASFFreeGamesPlugin.RegisterBot(Bot bot)
2023-11-19T10:49:33.042852086Z    at Maxisoft.ASF.ASFFreeGamesPlugin.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:33.042857165Z    at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
2023-11-19T10:49:33.042861832Z    at ArchiSteamFarm.Plugins.PluginsCore.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:33.043404314Z 2023-11-19 10:49:33|ArchiSteamFarm-18|INFO|pd3|IsAnythingToFarm() Checking first badge page...
2023-11-19T10:49:35.106233463Z 2023-11-19 10:49:35|ArchiSteamFarm-18|INFO|pd3|StartFarming() We don't have anything to farm on this account!
2023-11-19T10:49:40.272692763Z 2023-11-19 10:49:40|ArchiSteamFarm-18|INFO|aw|Connect() Connecting...
2023-11-19T10:49:40.818655670Z 2023-11-19 10:49:40|ArchiSteamFarm-18|INFO|aw|OnConnected() Connected to Steam!
2023-11-19T10:49:40.818674770Z 2023-11-19 10:49:40|ArchiSteamFarm-18|INFO|aw|OnConnected() Logging in...
2023-11-19T10:49:41.314912914Z 2023-11-19 10:49:41|ArchiSteamFarm-18|INFO|aw|OnLoggedOn() Successfully logged on as #####
2023-11-19T10:49:41.315165388Z 2023-11-19 10:49:41|ArchiSteamFarm-18|WARN|aw|OnLoggedOn() This account is limited, farming process is unavailable until the restriction is removed!
2023-11-19T10:49:41.315489456Z 2023-11-19 10:49:41|ArchiSteamFarm-18|INFO|aw|Init() Success!
2023-11-19T10:49:41.317006531Z 2023-11-19 10:49:41|ArchiSteamFarm-18|ERROR|ASF|OnBotLoggedOn() System.MissingMethodException: Method not found: 'UInt32 System.BitConverter.ToUInt32(System.ReadOnlySpan`1<Byte>)'.
2023-11-19T10:49:41.317019582Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextDouble()
2023-11-19T10:49:41.317024640Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextGaussian(Double mean, Double standardDeviation)
2023-11-19T10:49:41.317028526Z    at Maxisoft.ASF.CollectIntervalManager.GetRandomizedTimerDelay(Double meanSeconds, Double stdSeconds, Double minSeconds, Double maxSeconds)
2023-11-19T10:49:41.317032082Z    at Maxisoft.ASF.CollectIntervalManager.StartTimerIfNeeded()
2023-11-19T10:49:41.317035377Z    at Maxisoft.ASF.ASFFreeGamesPlugin.StartTimerIfNeeded()
2023-11-19T10:49:41.317041207Z    at Maxisoft.ASF.ASFFreeGamesPlugin.RegisterBot(Bot bot)
2023-11-19T10:49:41.317047988Z    at Maxisoft.ASF.ASFFreeGamesPlugin.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:41.317054087Z    at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
2023-11-19T10:49:41.317057503Z    at ArchiSteamFarm.Plugins.PluginsCore.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:42.383740255Z 2023-11-19 10:49:42|ArchiSteamFarm-18|INFO|aw|StartFarming() We don't have anything to farm on this account!
2023-11-19T10:49:50.275847961Z 2023-11-19 10:49:50|ArchiSteamFarm-18|INFO|csgo|Connect() Connecting...
2023-11-19T10:49:51.690034130Z 2023-11-19 10:49:51|ArchiSteamFarm-18|INFO|csgo|OnConnected() Connected to Steam!
2023-11-19T10:49:51.690053409Z 2023-11-19 10:49:51|ArchiSteamFarm-18|INFO|csgo|OnConnected() Logging in...
2023-11-19T10:49:52.495141999Z 2023-11-19 10:49:52|ArchiSteamFarm-18|INFO|csgo|OnLoggedOn() Successfully logged on as ####
2023-11-19T10:49:52.495581821Z 2023-11-19 10:49:52|ArchiSteamFarm-18|INFO|csgo|Init() Success!
2023-11-19T10:49:52.496669372Z 2023-11-19 10:49:52|ArchiSteamFarm-18|ERROR|ASF|OnBotLoggedOn() System.MissingMethodException: Method not found: 'UInt32 System.BitConverter.ToUInt32(System.ReadOnlySpan`1<Byte>)'.
2023-11-19T10:49:52.496687797Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextDouble()
2023-11-19T10:49:52.496695283Z    at Maxisoft.ASF.RandomUtils.GaussianRandom.NextGaussian(Double mean, Double standardDeviation)
2023-11-19T10:49:52.496715685Z    at Maxisoft.ASF.CollectIntervalManager.GetRandomizedTimerDelay(Double meanSeconds, Double stdSeconds, Double minSeconds, Double maxSeconds)
2023-11-19T10:49:52.496722629Z    at Maxisoft.ASF.CollectIntervalManager.StartTimerIfNeeded()
2023-11-19T10:49:52.496729854Z    at Maxisoft.ASF.ASFFreeGamesPlugin.StartTimerIfNeeded()
2023-11-19T10:49:52.496736106Z    at Maxisoft.ASF.ASFFreeGamesPlugin.RegisterBot(Bot bot)
2023-11-19T10:49:52.496742308Z    at Maxisoft.ASF.ASFFreeGamesPlugin.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:52.496748158Z    at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
2023-11-19T10:49:52.496755454Z    at ArchiSteamFarm.Plugins.PluginsCore.OnBotLoggedOn(Bot bot)
2023-11-19T10:49:54.088594838Z 2023-11-19 10:49:54|ArchiSteamFarm-18|INFO|csgo|IsAnythingToFarm() Checking first badge page...
`

using latest Pre-Release

**Comment by maxisoft** [comment] 2023-11-19 11:28
I have fixed the issue in the dev branch. 
I apologize for the inconvenience caused by this error. It occurred because I did not test the random interval feature on a trimmed ASF binary: I missed out this `System.MissingMethodException` error while doing internal testing on my own setup, because I had kept the random interval feature disabled in the configuration.

I am currently working on the issue #45 to improve the testing and release process of the plugin. 
I will publish a new release soon that will be compatible with trimmed ASF binaries. 

Thank you for your patience and feedback.

**Comment by kevindevm** [comment] 2023-12-15 22:51
to me it crash asf  can you help with that?

**Comment by JourneyOver** [comment] 2023-12-16 05:47
> to me it crash asf can you help with that?

well thats probably because this plugin hasn't been updated to support the newest version of ASF which is now on the .NET 8 platform so any plugins that don't support .net 8 are currently going to sit there and just crash ASF constantly.

**Comment by maxisoft** [comment] 2024-05-11 09:40
Hey all,

The `System.MissingMethodException` bug in #46 is now fixed with the latest plugin update (PR #65). No more crashes when using the plugin with ASF.

Make sure to update to version 1.5.1 for a smooth experience. Thanks for sticking around and for all the feedback that helped squash this bug.

- Maxisoft

**Closed by maxisoft** 2024-05-11 09:40 UTC
Labels: bug
