### ISSUE TITLE
Error when plugin running

### ISSUE THREAD

**Issue by gyq180** [maxisoft/ASFFreeGames#90] opened 2024-09-07 19:17 UTC
**Describe the bug**
Error when plugin running

**To Reproduce**
ASF log: ERROR ASF > CollectGames() Unable to load json from reddit RedditServerException: reddit http error code is Forbidden
I access reddit by Chrome, it is normal.

**Screenshots**
![image](https://github.com/user-attachments/assets/d26b895c-1a36-4ddf-ba2a-ee8b2d1114b5)

FreePackages 1.5.2.0
ASF 6.0.7.0

**Comment by maxisoft** [comment] 2024-09-08 06:50
Hi gyq180,

Thanks for reporting this issue! You're right, this is a duplicate of issue #75  where we're also tracking the "RedditServerException: reddit http error code is Forbidden" error.

I'm currently working on a solution in the dev branch that uses [redlib](https://github.com/redlib-org/redlib) as an alternative to the Reddit API. This should hopefully avoid these types of errors in the future. I'll complete, integrate and test this solution as soon as possible.

In the meantime, I'm closing this issue as a duplicate of [#75]. Please subscribe to that issue for updates on the fix.

Thanks again for your report!

**Closed by maxisoft** 2024-09-08 06:50 UTC
Labels: bug
